typography_spectrum: 0.5598165336996317
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7425114084035158
  lightness: 0.0035779012832790613
  saturation: 0.45182390534318984
  rhythmicContrast: 0.9752752284985036
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9074360344093293
analytics:
  google: null
  facebook: null
  twitter: null
name: God Sex Money
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'GOD:SEX:MONEY:'
description: The Three Biggest Issues
purpose: []
